import { Inter } from "next/font/google"
import "./globals.css"

import Children from "types"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default async function RootLayout({ children }: Children) {
    return (
        <html className={inter.className} data-theme="next" lang="en">
            <body className="bg-black text-base">{children}</body>
        </html>
    )
}
